#!/usr/bin/env bash
# configuring nginx so it listens to port 80
# nginx_likes_port_80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
